routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/auth/passport', function () {
    return view('debug');
});

Auth::routes();
Route::get('/', 'HomeController@index')->name('home')->middleware('auth');
Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');

Route::group(['middleware' => 'auth'], function () {
		Route::get('icons', ['as' => 'pages.icons', 'uses' => 'PageController@icons']);
		Route::get('maps', ['as' => 'pages.maps', 'uses' => 'PageController@maps']);
		Route::get('notifications', ['as' => 'pages.notifications', 'uses' => 'PageController@notifications']);
		Route::get('rtl', ['as' => 'pages.rtl', 'uses' => 'PageController@rtl']);
		Route::get('tables', ['as' => 'pages.tables', 'uses' => 'PageController@tables']);
		Route::get('typography', ['as' => 'pages.typography', 'uses' => 'PageController@typography']);
		Route::get('upgrade', ['as' => 'pages.upgrade', 'uses' => 'PageController@upgrade']);
});

Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'UserController', ['except' => ['show']]);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);

    Route::resource('item', 'ItemController', ['only' => ['index','create','edit']]);
    Route::resource('product-category', 'ProductCategoryController', ['only' => ['index','create','edit']]);
    Route::resource('client', 'ClientController', ['only' => ['index','create','edit']]);
    Route::resource('stockpile', 'StockpileController', ['only' => ['create','edit']]);
    Route::resource('invoice', 'InvoiceController',['only' => ['index','create','edit']]);

    Route::get('stockpile/{type}/warehouse', 'IntakeStockpileController@index')->name('rice.warehouse');
    Route::get('product/rice/load', 'ProductController@sendRiceView')->name('rice.load');
    Route::get('invoice/{filename}/{action}', 'InvoiceController@pdfRequestLink')->name('invoice.action');

});

Route::get('/debug','DebugController@index');

resources/views/layouts/navbars/navbar.blade.php
@auth()
    @include('layouts.navbars.navs.auth')
@endauth

@guest()
    @include('layouts.navbars.navs.guest')
@endguest

resources/views/layouts/navbars/sidebar.blade.php
<div class="sidebar">
    <div class="sidebar-wrapper">
        <div class="logo">
            <a href="#" class="simple-text logo-mini">{{ _('HRM') }}</a>
            <a href="#" class="simple-text logo-normal">{{ _('Hasinidu Rice Mill') }}</a>
        </div>
        <ul class="nav">
            <li @if ($pageSlug == 'dashboard') class="active " @endif>
                <a href="{{ route('home') }}">
                    <i class="tim-icons icon-chart-pie-36"></i>
                    <p>{{ _('Dashboard') }}</p>
                </a>
            </li>

            <li @if ($pageSlug == 'make-invoice') class="active " @endif>
                <a href="{{ route('invoice.create') }}">
                    <i class="tim-icons icon-notes"></i>
                    <p>{{ _('Make Invoice') }}</p>
                </a>
            </li>

            <li @if ($pageSlug == 'invoices') class="active " @endif>
                <a href="{{ route('invoice.index') }}">
                    <i class="tim-icons icon-bullet-list-67"></i>
                    <p>{{ _('Invoices') }}</p>
                </a>
            </li>

            <li @if ($pageSlug == 'items') class="active " @endif>
                <a href="{{ route('item.index') }}">
                    <i class="tim-icons icon-cart"></i>
                    <p>{{ _('Items') }}</p>
                </a>
            </li>

            <li @if ($pageSlug == 'product-category') class="active " @endif>
                <a href="{{ route('product-category.index') }}">
                    <i class="tim-icons icon-basket-simple"></i>
                    <p>{{ _('Products Category') }}</p>
                </a>
            </li>


            <li @if ($pageSlug == 'clients') class="active " @endif>
                <a href="{{ route('client.index') }}">
                    <i class="tim-icons icon-satisfied"></i>
                    <p>{{ _('Clients') }}</p>
                </a>
            </li>

            <li @if ($pageSlug == 'rice-warehouses') class="active " @endif>
                <a href="{{ route('rice.warehouse',['type'=>'rice']) }}">
                    <i class="tim-icons icon-app"></i>
                    <p>{{ _('Rice Warehouses') }}</p>
                </a>
            </li>
            <li @if ($pageSlug == 'stockpile') class="active " @endif>
                <a href="{{ route('rice.warehouse',['type'=>'paddy']) }}">
                    <i class="tim-icons icon-app"></i>
                    <p>{{ _('Stockpiles') }}</p>
                </a>
            </li>

            <li @if ($pageSlug == 'send-rice-to-stockpile') class="active " @endif>
                <a href="{{ route('rice.load') }}">
                    <i class="tim-icons icon-user-run"></i>
                    <p>{{ _('Load') }}</p>
                </a>
            </li>

        </ul>
    </div>
</div>